import { Code, Cpu, Globe, Award } from "lucide-react";
const About = () => {
    const highlights = [
        {
            icon: Code,
            title: "Full Stack Developer",
            description: "Experiência completa em desenvolvimento frontend e backend com tecnologias modernas.",
        },
        {
            icon: Cpu,
            title: "Hardware Specialist",
            description: "Conhecimento técnico em manutenção, montagem e upgrade de equipamentos.",
        },
        {
            icon: Globe,
            title: "Web Technologies",
            description: "Criação de sites, sistemas e aplicações web responsivas e otimizadas.",
        },
        {
            icon: Award,
            title: "Certified Professional",
            description: "Técnica em Informática com certificações em desenvolvimento e linguagens.",
        },
    ];
    const journey = [
        {
            year: "2023",
            title: "Início na Programação",
            description: "Primeiros passos com Python e lógica de programação..",
        },
        {
            year: "2023",
            title: "Desenvolvimento Web",
            description: "Aprofundamento em HTML, CSS, JavaScript e primeiros projetos web.",
        },
        {
            year: "2024",
            title: "Especialização Full Stack",
            description: "Domínio de tecnologias avançadas e início dos projetos profissionais.",
        },
    ];
    return (React.createElement("section", { id: "about", className: "py-20 px-4 sm:px-6 lg:px-8" },
        React.createElement("div", { className: "max-w-7xl mx-auto" },
            React.createElement("div", { className: "text-center mb-16 animate-fade-up" },
                React.createElement("p", { className: "font-mono text-accent text-sm uppercase tracking-wider mb-4" }, "Conhe\u00E7a minha hist\u00F3ria"),
                React.createElement("h2", { className: "text-4xl lg:text-6xl font-bold text-gradient mb-6" }, "Sobre Giordana")),
            React.createElement("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-16 items-center mb-20" },
                React.createElement("div", { className: "space-y-8 animate-fade-up" },
                    React.createElement("div", { className: "space-y-6" },
                        React.createElement("h3", { className: "text-3xl font-bold text-card-foreground" }, "Desenvolvedora Full Stack & T\u00E9cnica em Inform\u00E1tica"),
                        React.createElement("div", { className: "space-y-4 text-muted-foreground leading-relaxed" },
                            React.createElement("p", null,
                                "Ol\u00E1! Sou ",
                                React.createElement("span", { className: "text-accent font-semibold" }, "Giordana Stumm"),
                                ", uma desenvolvedora apaixonada por tecnologia e inova\u00E7\u00E3o. Minha jornada come\u00E7ou com a curiosidade sobre como as coisas funcionam no mundo digital."),
                            React.createElement("p", null,
                                "Tenho experi\u00EAncia s\u00F3lida em ",
                                React.createElement("span", { className: "text-accent" }, "desenvolvimento de interfaces modernas"),
                                "com HTML, CSS, JavaScript e Qt Designer, al\u00E9m de trabalhar no backend com",
                                React.createElement("span", { className: "text-accent" }, " Python, Java e MySQL"),
                                "."),
                            React.createElement("p", null,
                                "Minha forma\u00E7\u00E3o t\u00E9cnica tamb\u00E9m inclui ",
                                React.createElement("span", { className: "text-accent" }, "manuten\u00E7\u00E3o de hardware"),
                                ", o que me permite oferecer solu\u00E7\u00F5es completas, desde a concep\u00E7\u00E3o do software at\u00E9 a infraestrutura f\u00EDsica necess\u00E1ria."),
                            React.createElement("p", null,
                                "Acredito que a tecnologia deve ser acess\u00EDvel e funcional, sempre priorizando a ",
                                React.createElement("span", { className: "text-accent" }, "experi\u00EAncia do usu\u00E1rio"),
                                " e a",
                                React.createElement("span", { className: "text-accent" }, " qualidade do c\u00F3digo"),
                                "."))),
                    React.createElement("div", { className: "grid grid-cols-2 gap-6" },
                        React.createElement("div", { className: "text-center p-4 bg-gradient-card rounded-lg border border-card-border" },
                            React.createElement("div", { className: "text-2xl font-bold text-gradient mb-1" }, "2+"),
                            React.createElement("div", { className: "text-muted-foreground font-mono text-sm" }, "Anos Desenvolvendo")),
                        React.createElement("div", { className: "text-center p-4 bg-gradient-card rounded-lg border border-card-border" },
                            React.createElement("div", { className: "text-2xl font-bold text-gradient mb-1" }, "15+"),
                            React.createElement("div", { className: "text-muted-foreground font-mono text-sm" }, "Projetos Conclu\u00EDdos")))),
                React.createElement("div", { className: "flex justify-center animate-fade-in", style: { animationDelay: "0.3s" } },
                    React.createElement("div", { className: "relative" },
                        React.createElement("div", { className: "w-80 h-80 rounded-2xl bg-gradient-card p-1 hover-lift" },
                            React.createElement("div", { className: "w-full h-full rounded-xl bg-surface flex items-center justify-center overflow-hidden relative" },
                                React.createElement("div", { className: "absolute inset-0 bg-gradient-accent opacity-10" }),
                                React.createElement("div", { className: "relative z-10 text-center" },
                                    React.createElement("div", { className: "text-6xl mb-4" }, "\uD83D\uDC69\u200D\uD83D\uDCBB"),
                                    React.createElement("div", { className: "font-mono text-accent text-sm" }, "Giordana.dev")))),
                        React.createElement("div", { className: "absolute -top-4 -right-4 bg-accent rounded-full w-16 h-16 flex items-center justify-center animate-float shadow-accent" },
                            React.createElement(Code, { className: "w-8 h-8 text-accent-foreground" })),
                        React.createElement("div", { className: "absolute -bottom-4 -left-4 bg-surface-elevated rounded-full w-12 h-12 flex items-center justify-center animate-float border border-border", style: { animationDelay: "-1s" } },
                            React.createElement(Cpu, { className: "w-6 h-6 text-accent" }))))),
            React.createElement("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-20" }, highlights.map((item, index) => (React.createElement("div", { key: index, className: "text-center p-6 bg-gradient-card rounded-xl border border-card-border hover-lift animate-fade-up", style: { animationDelay: `${index * 0.1}s` } },
                React.createElement("div", { className: "mb-4" },
                    React.createElement(item.icon, { className: "w-12 h-12 text-accent mx-auto" })),
                React.createElement("h4", { className: "font-bold text-card-foreground mb-2" }, item.title),
                React.createElement("p", { className: "text-muted-foreground text-sm leading-relaxed" }, item.description))))),
            React.createElement("div", { className: "bg-gradient-card rounded-xl p-8 border border-card-border animate-fade-up" },
                React.createElement("div", { className: "text-center mb-12" },
                    React.createElement("h3", { className: "text-3xl font-bold text-gradient mb-4" }, "Minha Jornada"),
                    React.createElement("p", { className: "text-muted-foreground max-w-2xl mx-auto" }, "Uma evolu\u00E7\u00E3o constante na busca por conhecimento e excel\u00EAncia t\u00E9cnica")),
                React.createElement("div", { className: "space-y-8" }, journey.map((item, index) => (React.createElement("div", { key: index, className: "flex items-start space-x-6 group animate-slide-in", style: { animationDelay: `${index * 0.2}s` } },
                    React.createElement("div", { className: "flex-shrink-0" },
                        React.createElement("div", { className: "w-16 h-16 bg-gradient-accent rounded-full flex items-center justify-center group-hover:scale-110 transition-transform shadow-accent" },
                            React.createElement("span", { className: "font-mono font-bold text-accent-foreground" }, item.year))),
                    React.createElement("div", { className: "flex-1 min-w-0 pb-8" },
                        React.createElement("h4", { className: "text-xl font-bold text-card-foreground mb-2 group-hover:text-accent transition-colors" }, item.title),
                        React.createElement("p", { className: "text-muted-foreground leading-relaxed" }, item.description))))))))));
};
export default About;
