import { Mail, MessageCircle, Linkedin, Github, Instagram, MapPin, Clock } from "lucide-react";
import { Button } from "@/components/ui/button";
const Contact = () => {
    const contactMethods = [
        {
            icon: MessageCircle,
            title: "WhatsApp",
            description: "Resposta rápida para projetos e orçamentos",
            value: "+55 54 99952-7071",
            href: "https://wa.me/5554999527071",
            color: "from-green-500 to-emerald-500",
            primary: true,
        },
        {
            icon: Mail,
            title: "Email",
            description: "Para propostas mais detalhadas",
            value: "giordanastumm7@gmail.com",
            href: "mailto:giordanastumm7@gmail.com",
            color: "from-blue-500 to-indigo-500",
            primary: false,
        },
        {
            icon: Linkedin,
            title: "LinkedIn",
            description: "Conecte-se profissionalmente",
            value: "Giordana Stumm",
            href: "https://www.linkedin.com/in/giordana-stumm-13786133a",
            color: "from-blue-600 to-blue-800",
            primary: false,
        },
    ];
    const socialLinks = [
        {
            icon: Github,
            label: "GitHub",
            href: "https://github.com/gio0000",
            color: "hover:text-gray-400",
        },
        {
            icon: Instagram,
            label: "Instagram",
            href: "https://www.instagram.com/gio__tech",
            color: "hover:text-pink-400",
        },
    ];
    const info = [
        {
            icon: MapPin,
            text: "Carazinho, RS - Brasil",
        },
        {
            icon: Clock,
            text: "Seg-Sex: 8h às 18h",
        },
    ];
    return (React.createElement("section", { id: "contact", className: "py-20 px-4 sm:px-6 lg:px-8" },
        React.createElement("div", { className: "max-w-7xl mx-auto" },
            React.createElement("div", { className: "text-center mb-16 animate-fade-up" },
                React.createElement("p", { className: "font-mono text-accent text-sm uppercase tracking-wider mb-4" }, "Vamos trabalhar juntos"),
                React.createElement("h2", { className: "text-4xl lg:text-6xl font-bold text-gradient mb-6" }, "Entre em Contato"),
                React.createElement("p", { className: "text-muted-foreground text-lg max-w-3xl mx-auto" }, "Tem um projeto em mente? Precisa de suporte t\u00E9cnico? Ou quer apenas conversar sobre tecnologia? Estou sempre dispon\u00EDvel para ajudar!")),
            React.createElement("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-12" },
                React.createElement("div", { className: "space-y-8 animate-fade-up" },
                    React.createElement("div", null,
                        React.createElement("h3", { className: "text-2xl font-bold text-card-foreground mb-6" }, "Formas de Contato"),
                        React.createElement("div", { className: "space-y-6" }, contactMethods.map((method, index) => (React.createElement("a", { key: index, href: method.href, target: "_blank", rel: "noopener noreferrer", className: `block p-6 bg-gradient-card rounded-xl border hover-lift group transition-all duration-300 ${method.primary
                                ? "border-accent shadow-accent scale-102"
                                : "border-card-border hover:border-accent/30"}` },
                            React.createElement("div", { className: "flex items-start space-x-4" },
                                React.createElement("div", { className: `p-3 rounded-lg bg-gradient-to-r ${method.color} group-hover:scale-110 transition-transform` },
                                    React.createElement(method.icon, { className: "w-6 h-6 text-white" })),
                                React.createElement("div", { className: "flex-1" },
                                    React.createElement("div", { className: "flex items-center space-x-2 mb-2" },
                                        React.createElement("h4", { className: "font-bold text-card-foreground group-hover:text-accent transition-colors" }, method.title),
                                        method.primary && (React.createElement("span", { className: "px-2 py-1 text-xs font-mono bg-accent/10 text-accent rounded border border-accent/20" }, "Preferencial"))),
                                    React.createElement("p", { className: "text-muted-foreground text-sm mb-2" }, method.description),
                                    React.createElement("p", { className: "font-mono text-accent text-sm" }, method.value)))))))),
                    React.createElement("div", { className: "bg-gradient-card rounded-xl p-6 border border-card-border" },
                        React.createElement("h4", { className: "font-bold text-card-foreground mb-4" }, "Informa\u00E7\u00F5es Adicionais"),
                        React.createElement("div", { className: "space-y-3" }, info.map((item, index) => (React.createElement("div", { key: index, className: "flex items-center space-x-3" },
                            React.createElement(item.icon, { className: "w-5 h-5 text-accent" }),
                            React.createElement("span", { className: "text-muted-foreground font-mono text-sm" }, item.text))))))),
                React.createElement("div", { className: "animate-fade-up", style: { animationDelay: "0.2s" } },
                    React.createElement("div", { className: "bg-gradient-card rounded-xl p-8 border border-card-border h-full flex flex-col" },
                        React.createElement("div", { className: "text-center mb-8" },
                            React.createElement("div", { className: "w-20 h-20 bg-gradient-accent rounded-full flex items-center justify-center mx-auto mb-4 animate-float" },
                                React.createElement(MessageCircle, { className: "w-10 h-10 text-accent-foreground" })),
                            React.createElement("h3", { className: "text-2xl font-bold text-gradient mb-2" }, "Vamos Conversar!"),
                            React.createElement("p", { className: "text-muted-foreground" }, "A melhor forma de come\u00E7ar \u00E9 uma conversa simples")),
                        React.createElement("div", { className: "flex-1 space-y-6" },
                            React.createElement("div", { className: "grid grid-cols-1 gap-4" },
                                React.createElement(Button, { size: "lg", className: "bg-gradient-accent hover:shadow-accent hover-scale", asChild: true },
                                    React.createElement("a", { href: "https://wa.me/554999527071", target: "_blank", rel: "noopener noreferrer", className: "flex items-center justify-center gap-3" },
                                        React.createElement(MessageCircle, { className: "w-5 h-5" }),
                                        "Conversar no WhatsApp")),
                                React.createElement(Button, { size: "lg", variant: "outline", className: "hover-lift", asChild: true },
                                    React.createElement("a", { href: "mailto:giordanastumm7@gmail.com", className: "flex items-center justify-center gap-3" },
                                        React.createElement(Mail, { className: "w-5 h-5" }),
                                        "Enviar Email"))),
                            React.createElement("div", { className: "pt-6 border-t border-border" },
                                React.createElement("p", { className: "text-center text-muted-foreground text-sm mb-4 font-mono" }, "Ou me encontre nas redes sociais"),
                                React.createElement("div", { className: "flex justify-center space-x-6" }, socialLinks.map((social, index) => (React.createElement("a", { key: index, href: social.href, target: "_blank", rel: "noopener noreferrer", className: `p-3 rounded-lg bg-surface hover:bg-surface-hover transition-all duration-300 hover:scale-110 ${social.color}`, "aria-label": social.label },
                                    React.createElement(social.icon, { className: "w-6 h-6" }))))))),
                        React.createElement("div", { className: "mt-8 text-center" },
                            React.createElement("div", { className: "inline-flex items-center space-x-2 px-4 py-2 bg-accent/10 rounded-full border border-accent/20" },
                                React.createElement("div", { className: "w-2 h-2 bg-green-500 rounded-full animate-pulse" }),
                                React.createElement("span", { className: "font-mono text-sm text-accent" }, "Resposta em at\u00E9 2 horas")))))),
            React.createElement("div", { className: "text-center mt-16 animate-fade-up" },
                React.createElement("div", { className: "max-w-4xl mx-auto" },
                    React.createElement("blockquote", { className: "text-xl lg:text-2xl text-muted-foreground italic leading-relaxed" }, "\"A melhor forma de prever o futuro \u00E9 cri\u00E1-lo. Vamos construir algo incr\u00EDvel juntos!\""),
                    React.createElement("p", { className: "mt-4 font-mono text-accent" }, "\u2014 Giordana Stumm"))))));
};
export default Contact;
