import { Heart, Code, Coffee } from "lucide-react";
const Footer = () => {
    const currentYear = new Date().getFullYear();
    return (React.createElement("footer", { className: "border-t border-border bg-gradient-card" },
        React.createElement("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12" },
            React.createElement("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-8 mb-8" },
                React.createElement("div", { className: "space-y-4" },
                    React.createElement("div", { className: "flex items-center space-x-2" },
                        React.createElement("div", { className: "w-8 h-8 bg-gradient-accent rounded-lg flex items-center justify-center" },
                            React.createElement("span", { className: "font-mono text-sm font-bold text-white" }, "G")),
                        React.createElement("span", { className: "font-inter font-bold text-lg text-gradient" }, "Giordana.dev")),
                    React.createElement("p", { className: "text-muted-foreground text-sm leading-relaxed max-w-xs" }, "Desenvolvendo solu\u00E7\u00F5es digitais modernas com paix\u00E3o pela tecnologia e foco na experi\u00EAncia do usu\u00E1rio.")),
                React.createElement("div", { className: "space-y-4" },
                    React.createElement("h3", { className: "font-mono text-sm font-bold text-card-foreground uppercase tracking-wider" }, "Links R\u00E1pidos"),
                    React.createElement("ul", { className: "space-y-2" }, [
                        { href: "#about", label: "Sobre" },
                        { href: "#projects", label: "Projetos" },
                        { href: "#skills", label: "Habilidades" },
                        { href: "#services", label: "Serviços" },
                        { href: "#contact", label: "Contato" },
                    ].map((link) => (React.createElement("li", { key: link.href },
                        React.createElement("button", { onClick: () => { var _a; return (_a = document.querySelector(link.href)) === null || _a === void 0 ? void 0 : _a.scrollIntoView({ behavior: "smooth" }); }, className: "text-muted-foreground hover:text-accent transition-colors duration-200 text-sm font-mono hover:translate-x-1 transform" },
                            "\u2192 ",
                            link.label)))))),
                React.createElement("div", { className: "space-y-4" },
                    React.createElement("h3", { className: "font-mono text-sm font-bold text-card-foreground uppercase tracking-wider" }, "Contato"),
                    React.createElement("div", { className: "space-y-3" },
                        React.createElement("div", { className: "text-sm" },
                            React.createElement("span", { className: "text-muted-foreground font-mono" }, "Email: "),
                            React.createElement("a", { href: "mailto:giordanastumm7@gmail.com", className: "text-accent hover:text-accent/80 transition-colors" }, "giordanastumm7@gmail.com")),
                        React.createElement("div", { className: "text-sm" },
                            React.createElement("span", { className: "text-muted-foreground font-mono" }, "WhatsApp: "),
                            React.createElement("a", { href: "https://wa.me/554999527071", target: "_blank", rel: "noopener noreferrer", className: "text-accent hover:text-accent/80 transition-colors" }, "+55 49 9952-7071")),
                        React.createElement("div", { className: "text-sm" },
                            React.createElement("span", { className: "text-muted-foreground font-mono" }, "Local: "),
                            React.createElement("span", { className: "text-card-foreground" }, "Carazinho, RS"))))),
            React.createElement("div", { className: "border-t border-border my-8" }),
            React.createElement("div", { className: "flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0" },
                React.createElement("div", { className: "flex items-center space-x-2 text-muted-foreground text-sm" },
                    React.createElement("span", { className: "font-mono" },
                        "\u00A9 ",
                        currentYear,
                        " Giordana Stumm."),
                    React.createElement("span", null, "Todos os direitos reservados.")),
                React.createElement("div", { className: "flex items-center space-x-2 text-muted-foreground text-sm" },
                    React.createElement("span", { className: "font-mono" }, "Feito com"),
                    React.createElement(Heart, { className: "w-4 h-4 text-red-500 animate-pulse" }),
                    React.createElement(Code, { className: "w-4 h-4 text-accent" }),
                    React.createElement("span", { className: "font-mono" }, "e"),
                    React.createElement(Coffee, { className: "w-4 h-4 text-amber-500" }))),
            React.createElement("div", { className: "mt-6 pt-6 border-t border-border text-center" },
                React.createElement("p", { className: "text-muted-foreground text-xs font-mono" }, "Desenvolvido com React, TypeScript, Tailwind CSS e muito \u2615")))));
};
export default Footer;
